#ifndef _ELOG_CFG_H_
#define _ELOG_CFG_H_

#define ELOG_OUTPUT_ENABLE
#define ELOG_OUTPUT_LVL ELOG_LVL_INFO
#define ELOG_LINE_BUF_SIZE 256
#define ELOG_LINE_NUM_MAX_LEN 5
#define ELOG_FILTER_TAG_MAX_LEN 30
#define ELOG_FILTER_KW_MAX_LEN 16
#define ELOG_FILTER_TAG_LVL_MAX_NUM 5
#define ELOG_NEWLINE_SIGN "\r\n"

#define ELOG_COLOR_ENABLE
#define ELOG_FMT_USING_FUNC
#define ELOG_FMT_USING_LINE

#endif
